const teamData = [
  ["cardinals", "Arizona Cardinals", "ARI", "#97233f", "#ffb612"], ["falcons", "Atlanta Falcons", "ATL", "#a71930", "#000000"], ["ravens", "Baltimore Ravens", "BAL", "#241773", "#9e7c0c"], ["bills", "Buffalo Bills", "BUF", "#00338d", "#c60c30"], ["panthers", "Carolina Panthers", "CAR", "#0085ca", "#101820"], ["bears", "Chicago Bears", "CHI", "#0b162a", "#c83803"], ["bengals", "Cincinnati Bengals", "CIN", "#fb4f14", "#000000"], ["browns", "Cleveland Browns", "CLE", "#311d00", "#ff3c00"], ["cowboys", "Dallas Cowboys", "DAL", "#003594", "#869397"], ["broncos", "Denver Broncos", "DEN", "#fb4f14", "#002244"], ["lions", "Detroit Lions", "DET", "#0076b6", "#b0b7bc"], ["packers", "Green Bay Packers", "GB", "#203731", "#ffb612"], ["texans", "Houston Texans", "HOU", "#03202f", "#a71930"], ["colts", "Indianapolis Colts", "IND", "#002c5f", "#a2aaad"], ["jaguars", "Jacksonville Jaguars", "JAX", "#006778", "#d7a22a"], ["chiefs", "Kansas City Chiefs", "KC", "#e31837", "#ffb81c"], ["raiders", "Las Vegas Raiders", "LV", "#000000", "#a5acaf"], ["chargers", "Los Angeles Chargers", "LAC", "#0080c6", "#ffc20e"], ["rams", "Los Angeles Rams", "LA", "#003594", "#ffa300"], ["dolphins", "Miami Dolphins", "MIA", "#008e97", "#fc4c02"], ["vikings", "Minnesota Vikings", "MIN", "#4f2683", "#ffc62f"], ["patriots", "New England Patriots", "NE", "#002244", "#c60c30"], ["saints", "New Orleans Saints", "NO", "#d3bc8d", "#101820"], ["giants", "New York Giants", "NYG", "#0b2265", "#a71930"], ["jets", "New York Jets", "NYJ", "#125740", "#000000"], ["eagles", "Philadelphia Eagles", "PHI", "#004c54", "#a5acaf"], ["steelers", "Pittsburgh Steelers", "PIT", "#101820", "#ffb612"], ["49ers", "San Francisco 49ers", "SF", "#aa0000", "#b3995d"], ["seahawks", "Seattle Seahawks", "SEA", "#002244", "#69be28"], ["buccaneers", "Tampa Bay Buccaneers", "TB", "#d50a0a", "#34302b"], ["titans", "Tennessee Titans", "TEN", "#0c2340", "#4b92db"], ["commanders", "Washington Commanders", "WAS", "#5a1414", "#ffb612"]
];
const teams = Object.fromEntries(teamData.map(([key, name, abbr, primary, secondary]) => [key, { name, abbr, primary, secondary, record: "2026 season · NFL", roster: [`${abbr} Quarterback`, `${abbr} Runner`, `${abbr} X Receiver`, `${abbr} Z Receiver`, `${abbr} Tight End`, `${abbr} Left Tackle`, `${abbr} Left Guard`, `${abbr} Center`, `${abbr} Right Guard`, `${abbr} Right Tackle`, `${abbr} Fullback`] }]));
teams.seahawks.roster = ["Sam Darnold", "Kenneth Walker III", "Jaxon Smith-Njigba", "Cooper Kupp", "Rashid Shaheed", "AJ Barner", "Charles Cross", "Grey Zabel", "Jalen Sundell", "Leonard Williams", "Devon Witherspoon"];
const teamKeys = teamData.map(([key]) => key);
const offenseShape = [["QB", 22, 51], ["RB", 25, 59], ["WR", 20, 22], ["WR", 22, 79], ["TE", 30, 38], ["LT", 30, 39], ["LG", 30, 44], ["C", 30, 50], ["RG", 30, 56], ["RT", 30, 61], ["FB", 26, 51]];
const receiverShape = { D: [25, 59], A: [20, 22], W: [22, 79], S: [30, 38] };
const defenseShape = [["CB", 44, 19], ["S", 57, 25], ["DE", 41, 38], ["DT", 43, 46], ["NT", 47, 51], ["DT", 43, 56], ["DE", 41, 64], ["LB", 51, 40], ["LB", 53, 63], ["CB", 44, 80], ["S", 67, 28]];
const routes = { W: [30, -13, 18, "DEEP OUT"], A: [25, 9, 14, "SLUGGO"], S: [20, -6, 11, "CROSS"], D: [18, 15, 9, "FLAT"], };
const $ = (id) => document.getElementById(id); const field = $("field");
let selectedTeam = "seahawks", opponentIndex = teamKeys.indexOf("patriots"), yards = 0, plays = 0, score = 0, gameSeconds = 300, down = 1, distance = 10, fieldPosition = 25, playLive = false, openReceiver = "D", scrimmageX = 30, firstDownX = 40;
function opponent() { return teams[teamKeys[opponentIndex]]; }
function player(name, role, x, y, side, receiverKey) { const node = document.createElement("div"); const line = ["LT", "LG", "C", "RG", "RT", "FB"].includes(role) ? " lineman-player" : ""; node.className = `stick-player ${side}-player ${role.toLowerCase()}-player${line}`; node.style.left = `${x}%`; node.style.top = `${y}%`; node.dataset.name = name; node.dataset.role = role; if (receiverKey) node.dataset.receiver = receiverKey; if (role === "QB") node.id = "quarterback"; node.innerHTML = `<span class="stick-head"></span><span class="stick-body"></span><span class="stick-arms"></span><span class="stick-legs"></span><b class="player-label">${name}<small>${role}</small></b><strong class="route-key">${receiverKey || ""}</strong>`; return node; }
function renderPlayers() { const offense = $("offensePlayers"), defense = $("defensePlayers"), home = teams[selectedTeam], away = opponent(); offense.replaceChildren(); defense.replaceChildren(); const keys = { 1: "D", 2: "A", 3: "W", 4: "S" }; home.roster.forEach((name, index) => { const [role, x, y] = offenseShape[index]; offense.appendChild(player(role === "QB" ? `${home.abbr} QB` : name, role, x, y, "offense", keys[index])); }); away.roster.forEach((name, index) => { const [role, x, y] = defenseShape[index]; defense.appendChild(player(name, role, x, y, "defense")); }); $("awayLabel").textContent = away.abbr; $("opponentName").textContent = away.name; $("possessionText").textContent = `${home.abbr} BALL`; setOpenReceiver(); }
function setOpenReceiver() { document.querySelectorAll(".offense-player").forEach((node) => node.classList.remove("open-receiver", "covered-receiver")); const target = document.querySelector(`[data-receiver="${openReceiver}"]`); if (target) target.classList.add("open-receiver"); }
function updateTeam() { const team = teams[selectedTeam]; document.documentElement.style.setProperty("--team-primary", team.primary); document.documentElement.style.setProperty("--team-secondary", team.secondary); $("teamName").textContent = team.name; $("teamRecord").textContent = team.record; $("homeLabel").textContent = team.abbr; renderPlayers(); }
function updateStats() { $("yards").textContent = yards; $("plays").textContent = plays; $("homeScore").textContent = score; $("possession").textContent = `${Math.floor(gameSeconds / 60)}:${String(gameSeconds % 60).padStart(2, "0")}`; const suffix = ["th", "st", "nd", "rd"][down] || "th"; $("downDistance").innerHTML = `${down}${suffix} &amp; ${distance}`; $("playText").textContent = `${down}${suffix} & ${distance} · OWN ${fieldPosition}`; $("driveSummary").textContent = `${teams[selectedTeam].abbr} ball at the ${fieldPosition}`; $("clock").textContent = `${Math.floor(gameSeconds / 60)}:${String(gameSeconds % 60).padStart(2, "0")}`; }
function toast(message) { const display = $("fieldToast"); display.textContent = message; display.classList.remove("show"); void display.offsetWidth; display.classList.add("show"); }
function resetPlay() { const shift = scrimmageX - 30; const qb = $("quarterback"); if (qb) { qb.style.left = `${22 + shift}%`; qb.style.top = "51%"; qb.classList.remove("running"); } document.querySelectorAll(".offense-player").forEach((node) => { const shape = node.dataset.receiver ? receiverShape[node.dataset.receiver] : offenseShape.find((entry) => entry[0] === node.dataset.role)?.slice(1); if (shape) { node.style.left = `${Math.min(88, shape[0] + shift)}%`; node.style.top = `${shape[1]}%`; } }); document.querySelectorAll(".defense-player").forEach((node, index) => { node.style.left = `${Math.min(88, defenseShape[index][1] + shift)}%`; node.style.top = `${defenseShape[index][2]}%`; node.classList.remove("rushing", "coverage-player"); }); }
function move(dx, dy) { if (!playLive) return; const qb = $("quarterback"); qb.style.left = `${Math.max(12, Math.min(83, parseFloat(qb.style.left) + dx * 2))}%`; qb.style.top = `${Math.max(11, Math.min(87, parseFloat(qb.style.top) + dy * 2))}%`; qb.classList.add("running"); }
function hike() { if (playLive) return; resetPlay(); openReceiver = ["W", "A", "S", "D"][Math.floor(Math.random() * 4)]; setOpenReceiver(); playLive = true; field.classList.add("play-live"); toast("HIKE!"); $("playStatus").textContent = `CPU defense is closing. ${routes[openReceiver][3]} is open; pass with ${openReceiver}.`; document.querySelectorAll(".defense-player").forEach((node, index) => { node.style.left = `${Math.min(80, parseFloat(node.style.left) + (index % 3) * 2)}%`; node.classList.add("rushing"); }); ["W", "A", "S", "D"].filter((key) => key !== openReceiver).forEach((key, index) => { const target = document.querySelector(`[data-receiver="${key}"]`), defender = document.querySelectorAll(".defense-player")[index]; if (target && defender) { target.classList.add("covered-receiver"); defender.classList.add("coverage-player"); defender.style.left = `${parseFloat(target.style.left) + 4}%`; defender.style.top = target.style.top; } }); }
function pass(receiver) { if (!playLive) { $("playStatus").textContent = "Press ↓ to hike before choosing a pass."; return; } const [dx, dy, routeGain, name] = routes[receiver], target = document.querySelector(`[data-receiver="${receiver}"]`), ball = $("ball"); plays += 1; gameSeconds = Math.max(0, gameSeconds - 8); playLive = false; field.classList.remove("play-live"); if (receiver !== openReceiver || !target) { toast("INCOMPLETE!"); finishDown(0, false); return; } const gain = Math.max(3, Math.min(distance + 8, routeGain + Math.floor(Math.random() * 7) - 3)); const x = Math.min(90, parseFloat(target.style.left) + dx); const y = Math.max(10, Math.min(88, parseFloat(target.style.top) + dy)); target.style.left = `${x}%`; target.style.top = `${y}%`; target.classList.add("catching"); ball.style.left = `${x}%`; ball.style.top = `${y}%`; ball.style.opacity = "1"; $("playStatus").textContent = `${target.dataset.name} completed the ${name} for ${gain} yards.`; setTimeout(() => { ball.style.opacity = "0"; target.classList.remove("catching"); toast("COMPLETE!"); finishDown(gain, true); }, 520); }
function finishDown(gain, complete) { if (complete) { yards += gain; fieldPosition += gain; distance -= gain; if (distance <= 0) { down = 1; distance = 10; scrimmageX = Math.min(78, scrimmageX + Math.min(14, gain * .72)); firstDownX = Math.min(88, scrimmageX + 10); $("playStatus").textContent = "First down! The offense moves up to the new line of scrimmage."; toast("FIRST DOWN!"); } else { down += 1; scrimmageX = Math.min(78, scrimmageX + Math.min(14, gain * .72)); firstDownX = Math.min(88, scrimmageX + distance * .72); $("playStatus").textContent = `Gain of ${gain}. The ball is now at the ${fieldPosition}.`; } } else if (down === 4) { endGame("Turnover on downs. New opponent loading..."); return; } else { down += 1; $("playStatus").textContent = `Incomplete pass. ${down}${["th", "st", "nd", "rd"][down] || "th"} down from the line of scrimmage.`; } if (fieldPosition >= 100) { score += 7; endGame("Touchdown! New opponent loading..."); return; } resetPlay(); updateStats(); }
function shiftFormation() { $("scrimmageLine").style.left = `${scrimmageX}%`; $("firstDown").style.left = `${firstDownX}%`; }
function endGame(message) { opponentIndex = (opponentIndex + 1) % teamKeys.length; playLive = false; resetPlay(); updateTeam(); $("playStatus").textContent = `${message} You now face ${opponent().name}. Restart for a fresh score.`; updateStats(); toast(`NEXT: ${opponent().abbr}`); }
function resetGame() { yards = 0; plays = 0; score = 0; gameSeconds = 300; down = 1; distance = 10; fieldPosition = 25; scrimmageX = 30; firstDownX = 40; openReceiver = "D"; field.classList.remove("play-live"); resetPlay(); $("scrimmageLine").style.left = `${scrimmageX}%`; $("firstDown").style.left = `${firstDownX}%`; $("playStatus").textContent = "Press ↓ to hike, then choose a route."; updateStats(); toast("KICKOFF"); }
$("teamSelect").replaceChildren(...teamData.map(([key, name]) => new Option(name, key))); $("teamSelect").value = selectedTeam; $("teamSelect").addEventListener("change", (event) => { selectedTeam = event.target.value; opponentIndex = (teamKeys.indexOf(selectedTeam) + 1) % teamKeys.length; updateTeam(); resetGame(); }); $("restartButton").addEventListener("click", resetGame);
document.addEventListener("keydown", (event) => { const key = event.key.toLowerCase(); if (["arrowup", "arrowdown", "arrowleft", "arrowright", "w", "a", "s", "d"].includes(key)) event.preventDefault(); if (key === "arrowdown") hike(); if (key === "arrowup") move(0, -4); if (key === "arrowleft") move(-4, 0); if (key === "arrowright") move(4, 0); if (["w", "a", "s", "d"].includes(key)) pass(key.toUpperCase()); });
updateTeam(); updateStats(); setInterval(() => { if (gameSeconds > 0) { gameSeconds -= 1; updateStats(); } }, 1000);
